/*
  resources (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  url VARCHAR(255),
  creator_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
*/

--  1 - 33 usser.id

INSERT INTO resources (title, description, url, image_url, creator_id)
VALUES  ('CSS Tricks Box-Shadow', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'https://css-tricks.com/almanac/properties/b/box-shadow/', 'https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80', 33),
 ('JS Fiddle', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 'http://jsfiddle.net/', 'https://cdn2.hubspot.net/hubfs/2174253/Blog/Developer%20Blog/Dev%20Blog%20Images/blog_jsfiddle.jpg', 12),
 ('ultrices mattis odio donec vitae nisi', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 'https://google.com', 'https://static01.nyt.com/images/2020/10/21/business/21Googleworld-illo/30Googleworld-illo-mobileMasterAt3x.jpg', 1),
 ('maecenas tristique est et', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'http://jsfiddle.net/', 'https://upload.wikimedia.org/wikipedia/commons/f/f9/Jsfiddle-logo.png', 14),
 ('penatibus et magnis', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', 'https://jquery.com/', 'https://images.unsplash.com/photo-1585076641399-5c06d1b3365f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80', 4),
 ('Mongo DB', 'While a table might seem like a good place to store data, as you can see from the example above, there are fields in this data set that require multiple values and would not be easy to search or display if modeled in a single column (for example – size and tags).

In a SQL database you might solve this problem by creating a relational table.

In MongoDB, data is stored as documents. These documents are stored in MongoDB in JSON (JavaScript Object Notation) format. JSON documents support embedded fields, so related data and lists of data can be stored with the document instead of an external table.

JSON is formatted as name/value pairs. In JSON documents, fieldnames and values are separated by a colon, fieldname and value pairs are separated by commas, and sets of fields are encapsulated in “curly braces” ({}).', 'https://www.mongodb.com/', 'https://insights.dice.com/wp-content/uploads/2019/04/MongoDB-Realm-Acquisition-Dice.png', 15),
 ('Intro to SQL', 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', 'https://www.w3schools.com/sql/sql_intro.asp', 'https://miro.medium.com/max/1334/1*Jrc_LmNnA-EG0-G5ava1nA.png', 4),
 ('arcu libero rutrum', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'https://www.barnesandnoble.com/', 'https://images.unsplash.com/photo-1512820790803-83ca734da794?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1374&q=80', 7),
 ('CSS Tricks Align-Items', 'In blandit ultrices enim.', 'https://css-tricks.com/almanac/properties/a/align-items/', 'https://css-tricks.com/wp-content/uploads/2020/12/social-default.png', 30),
 ('pede justo eu massa donec', 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 'https://www.w3schools.com/python/default.asp', 'https://media.wired.com/photos/5e59a85635982c0009f6eb8a/master/w_2240,c_limit/python-popularity.jpg', 22),
 ('posuere felis sed', 'In congue.', 'https://www.docker.com/', 'https://developers.redhat.com/sites/default/files/styles/article_feature/public/blog/2014/05/homepage-docker-logo.png?itok=zx0e-vcP', 1),
 ('vestibulum quam sapien varius', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', 'https://jquery.com/', 'https://media.wired.com/photos/5e59a85635982c0009f6eb8a/master/w_2240,c_limit/python-popularity.jpg', 19),
 ('What is Digital Ocean?', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'https://docs.digitalocean.com/', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7hoBnkVa80J4cL5E7FRhctcTXjO7AmpYfiN34B867MnXcdBcBC95cScMu2weTsl0VLH4&usqp=CAU', 15),
 ('Explore the Vercel Way', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 'https://vercel.com/', 'https://assets.vercel.com/image/upload/q_auto/front/vercel/dps.png', 29),
 ('Best Layouts - CSS Masonry', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', 'https://masonry.desandro.com/', 'https://media.wired.com/photos/5e59a85635982c0009f6eb8a/master/w_2240,c_limit/python-popularity.jpg', 24),

 ('Intro to Preact', 'Preact X is a huge step forward from Preact 8.x. We have rethought every bit and byte of our code and added a plethora of major features in the process. Same goes for compatibility enhancements to support more third-party libraries. In a nutshell Preact X is what we always wanted Preact to be: A tiny, fast and feature-packed library. And speaking of size, you will be happy to hear that all the new features and improved rendering fit into the same size footprint as 8.x!', 'https://preactjs.com/', 'https://preactjs.com/assets/app-icon.png', 10),

 ('maecenas pulvinar lobortis est phasellus sit amet', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 'https://jquery.com/', 'https://media.wired.com/photos/5e59a85635982c0009f6eb8a/master/w_2240,c_limit/python-popularity.jpg', 17),
 ('in tempor turpis nec euismod scelerisque', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'https://www.barnesandnoble.com/', 'https://images.unsplash.com/photo-1485322551133-3a4c27a9d925?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80', 29),

('Cute otters', 'Otters at the Toronto zoo', 'https://www.torontozoo.com/img/1200/20190417030828061NorthAmericanRiverOtter2.jpg', 'https://www.torontozoo.com/img/1200/20190417030828061NorthAmericanRiverOtter2.jpg',9),
('Code inspirtation', 'Get inspired by the great ourtdoors... Just kidding, we`re developers!' ,'https://images.unsplash.com/photo-1534972195531-d756b9bfa9f2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80', 'https://images.unsplash.com/photo-1534972195531-d756b9bfa9f2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80', 18),
('Grizzly Giant Sequoia Tree', '26th largest sequoia tree in the world, located at Yosemite Park', 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Grizzly_Giant_Mariposa_Grove.jpg', 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Grizzly_Giant_Mariposa_Grove.jpg', 21),
 ('cursus id turpis integer', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', 'https://preactjs.com/' ,'https://images.unsplash.com/photo-1592609931095-54a2168ae893?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80', 9),
 ('morbi sem mauris laoreet ut', 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 'https://www.barnesandnoble.com/', 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80', 16),
 ('Guide to AWS', 'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'https://docs.aws.amazon.com/index.html?nc2=h_ql_doc', 'https://dunhamconnect.com/wp-content/uploads/aws-migration.jpg', 2),
 ('cum sociis natoque penatibus et magnis', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', 'https://www.barnesandnoble.com/', 'https://images.unsplash.com/photo-1474366521946-c3d4b507abf2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80', 28),
 ('Postgres UUID Types - How To Use Them', 'The data type uuid stores Universally Unique Identifiers (UUID) as defined by RFC 4122, ISO/IEC 9834-8:2005, and related standards. (Some systems refer to this data type as a globally unique identifier, or GUID, instead.) This identifier is a 128-bit quantity that is generated by an algorithm chosen to make it very unlikely that the same identifier will be generated by anyone else in the known universe using the same algorithm. Therefore, for distributed systems, these identifiers provide a better uniqueness guarantee than sequence generators, which are only unique within a single database.', 'https://www.postgresql.org/docs/9.1/datatype-uuid.html', 'https://www.zdnet.com/a/hub/i/r/2018/04/19/092cbf81-acac-4f3a-91a1-5a26abc1721f/thumbnail/770x578/5d78c50199e6a9242367b37892be8057/postgresql-logo.png', 22),
 ('nisl nunc nisl duis bibendum felis sed', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'https://www.barnesandnoble.com/', 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80', 5),
 ('purus sit amet nulla quisque arcu libero', 'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', 'https://masonry.desandro.com/', 'https://codeconvey.com/wp-content/uploads/2020/04/pure-css-masonry-layout-with-flexbo.png', 2),
 ('nunc donec quis orci', 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', 'https://jquery.com/', 'https://images.unsplash.com/photo-1472437774355-71ab6752b434?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1267&q=80', 28),
 ('How To With Heroku', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', 'https://devcenter.heroku.com/', 'https://uploads.sitepoint.com/wp-content/uploads/2016/04/1461122387heroku-logo.jpg', 10),
 ('augue quam sollicitudin vitae consectetuer eget rutrum', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 'https://devcenter.heroku.com/', 'https://railsware.com/blog/wp-content/uploads/2018/11/HerokuvsAWS-icon.png', 15),
 ('Webhooks', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'https://www.contentful.com/developers/docs/concepts/webhooks/', 'https://cdn-assets-eu.frontify.com/s3/frontify-enterprise-files-eu/eyJwYXRoIjoid2VhcmVcL2FjY291bnRzXC82ZVwvNDAwMDM4OFwvcHJvamVjdHNcLzk4NFwvYXNzZXRzXC8xY1wvOTEwMDFcL2Q2OGI4ODc4ZWM5MmZiZjVhYWI1ZjVkMzVlZDE5YzBhLTE2MjM2NjA0MzYucG5nIn0:weare:7iEamADqfW53FDvNkrRuz9GoGCE4NNvG3SyfkFKfguY?width=850&height=552', 23),
 ('commodo vulputate justo in blandit ultrices enim', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', 'https://www.contentful.com/', 'https://pbs.twimg.com/profile_images/1407265748775489540/Ih0SLi89_400x400.jpg', 5);

